name: build-and-push
on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: https://github.com/containers/kubernetes-mcp-server.git#main
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/k8s-mcp-server:latest
            ghcr.io/${{ github.repository_owner }}/k8s-mcp-server:${{ github.ref_name }}